Added sanity checks for the create a streaming replicant script  (slave_spawn_from_master.erb) Checks include: 		-Check that user postgres is executing the script 		-Check that the masters ip address was supplied 		-Check If Postgres Is Running On the Remote Host 		-Check If Master Is Actually A Master

diff --git a/postgres/templates/slave_spawn_from_master.erb b/postgres/templates/slave_spawn_from_master.erb
--- a/postgres/templates/slave_spawn_from_master.erb
+++ b/postgres/templates/slave_spawn_from_master.erb
@@ -7,10 +7,9 @@ sourcehost=$1
 datadir=/var/lib/postgresql/9.2/main
 archivedir=/var/lib/postgresql/9.2/archive
 archivedirdest=/var/lib/postgresql/9.2/archive
-whoami=$(whoami)
 
 
-	if [[ "$whoami" != "postgres" ]]
+	if [[ `whoami` != "postgres" ]]
 	then
 	      echo "This script must be run as user Postgres"
 	      exit 1
@@ -23,11 +22,44 @@ whoami=$(whoami)
 		echo
 	exit 1
 	fi
-	     
+	    
+
+CheckIfPostgresIsRunningOnRemoteHost () {
+isrunning=$(ssh postgres@192.168.6.170 'if 'killall -0 postgres'; then echo "postgres_running"; else echo "postgress_not_running"; fi;')
+
+if [[ "$isrunning" = "postgress_not_running" ]]
+then
+        echo "postgres not running on the master, exiting";
+        exit 1
+elif [[ "$isrunning" = "postgres_running" ]]
+then
+        echo "postgres running on remote host";
+
+elif echo "unexpected response, exiting"
+then
+        exit 1
+fi
+}
 
 
+CheckIfMasterIsActuallyAMaster () {
+ismaster=$(ssh postgres@192.168.6.170 'if [ -f /var/lib/postgresql/9.2/main/recovery.conf ]; then echo "postgres_is_not_master"; else echo "postgres_is_a_master_instance"; fi;')
 
-#if cat /var/lib/postgresql/.ssh/authorized_keys 
+if [[ "$ismaster" = "postgres_is_not_master" ]]
+then
+        echo "postgres is already running as a slave, exiting";
+        exit 1
+
+elif [[ "$ismaster" = "postgres_is_a_master_instance" ]]
+then
+       echo "postgres is running as master (probably)";
+elif echo "unexpected response, exiting"
+then
+        exit 1
+
+fi
+}
+
 
 #Keepalived will trigger failover when it detects postgres stopping on the master node. -- this disables failover (/usr/sbin/check_postgres source:puppet:/keepalived/templates/check_postgres.erb) is a requirement
 DontFailOverDuringThisOperation () {
@@ -36,14 +68,26 @@ ssh postgres@$sourcehost "touch /tmp/dont_fail_over"
 }
 
 
-#TODO Check to see if master is actually a master
-#TODO check to see if this machien can become a slave (/var/lib/postgresql/9.2/main/recovery.conf source: ./postgres/templates/slave_recovery.erb) is a requirement)
+
+
 #prepare local server to become the new slave server. 
 PrepareLocalServer () {
 rm /tmp/trigger_file
 bash /etc/init.d/postgresql stop
 mv <%= @data_dir %>/recovery.done <%= @data_dir %>/recovery.conf
 }
+
+
+CheckForRecoveryConfig () {
+	if [ -e "<%= @data_dir %>/recovery.conf" ];
+	    then
+		echo "Slave Config File Found, Continuing"
+	    else
+		echo "Recovery.conf not found Postgres Cannot Become a Slave, Exiting"
+		exit 1
+	fi
+}
+
 
 #put master into  backup mode
 PutMasterIntoBackupMode () {
@@ -83,8 +127,11 @@ ssh postgres@$sourcehost "rm /tmp/dont_fail_over"
 
 #Execute above operations
 
+CheckIfPostgresIsRunningOnRemoteHost
+CheckIfMasterIsActuallyAMaster
 DontFailOverDuringThisOperation
 PrepareLocalServer
+CheckForRecoveryConfig
 PutMasterIntoBackupMode
 RsyncWhileLive
 StopBackupModeAndArchiveIntoWallLog
